import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import './Cart.css';
export const Cart = ({ cart, removeFromCart, updateQuantity, total }) => {
  const [reviewing, setReviewing] = useState(false);
  const money = value => new Intl.NumberFormat('en-GB', {style:'currency',currency:'EUR'}).format(value);
  return <section className="cart-container"><h1>Your basket</h1><p>Portfolio demonstration. Prices and availability are illustrative; no orders or payments are processed.</p>
    {cart.length === 0 ? <div className="empty-cart"><p>Your basket is empty.</p><Link to="/ourart">Explore the collection →</Link></div> : <><div className="cart-items">{cart.map(item => <article className="cart-item" key={item.id}><div className="cart-item-image"><img src={item.imgSrc} alt={item.name} /></div><div className="cart-item-details"><h2>{item.name}</h2><p>{item.selectedSize} · {item.selectedColor}</p><p>{money(item.price)}</p><div className="quantity-controls"><button aria-label={`Decrease quantity of ${item.name}`} onClick={() => {updateQuantity(item.id, item.quantity - 1); setReviewing(false);}}>−</button><span aria-label="Quantity">{item.quantity}</span><button aria-label={`Increase quantity of ${item.name}`} onClick={() => {updateQuantity(item.id, item.quantity + 1); setReviewing(false);}}>+</button></div><button onClick={() => {removeFromCart(item.id); setReviewing(false);}}>Remove {item.name}</button></div><strong>{money(item.price * item.quantity)}</strong></article>)}</div><div className="cart-summary"><p>Items subtotal <strong>{money(total)}</strong></p><p>Delivery and taxes are not calculated in this concept.</p><button className="okoa-button" onClick={() => setReviewing(true)}>Preview order</button></div>{reviewing && <div role="status" className="cart-summary"><h2>Order preview</h2><p>{cart.reduce((count,item) => count + item.quantity,0)} items · {money(total)}</p><p>This is a demonstration. No order has been placed and nothing has been charged.</p><Link to="/ourart">Continue browsing →</Link></div>}</>}
  </section>;
};
